//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeraAI.API.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OthersResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OthersResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeraAI.API.Resources.Resources.OthersResources", typeof(OthersResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration option not expected;.
        /// </summary>
        public static string ENUM_OPTION_NOT_EXPECTED {
            get {
                return ResourceManager.GetString("ENUM_OPTION_NOT_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General exception:.
        /// </summary>
        public static string OTHERS_EXCEPTION_PREFIX_ERROR {
            get {
                return ResourceManager.GetString("OTHERS_EXCEPTION_PREFIX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database returned more than one record for the given filter identifier;.
        /// </summary>
        public static string OTHERS_INVALID_NUMBER_OF_RECORDS_BASED_ON_IDENTIFIER_FILTER {
            get {
                return ResourceManager.GetString("OTHERS_INVALID_NUMBER_OF_RECORDS_BASED_ON_IDENTIFIER_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records were returned from database;.
        /// </summary>
        public static string OTHERS_NO_RECORDS_RETURNED_FROM_DATABASE {
            get {
                return ResourceManager.GetString("OTHERS_NO_RECORDS_RETURNED_FROM_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the sort columns must be valid..
        /// </summary>
        public static string OTHERS_NO_VALID_OPTION {
            get {
                return ResourceManager.GetString("OTHERS_NO_VALID_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ammount of records per page exceeded the max limit..
        /// </summary>
        public static string OTHERS_PAGE_SIZE_EXCEEDED {
            get {
                return ResourceManager.GetString("OTHERS_PAGE_SIZE_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records on the database were affected;.
        /// </summary>
        public static string OTHERS_UNEXPECTED_NUMBER_OF_AFFECTED_RECORDS_0 {
            get {
                return ResourceManager.GetString("OTHERS_UNEXPECTED_NUMBER_OF_AFFECTED_RECORDS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one record on the database was affetcted;.
        /// </summary>
        public static string OTHERS_UNEXPECTED_NUMBER_OF_AFFECTED_RECORDS_MORE_THAN {
            get {
                return ResourceManager.GetString("OTHERS_UNEXPECTED_NUMBER_OF_AFFECTED_RECORDS_MORE_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were unvalid matches in your search crieria..
        /// </summary>
        public static string OTHERS_UNMATCHED_SORT_WORDS {
            get {
                return ResourceManager.GetString("OTHERS_UNMATCHED_SORT_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings element already defined..
        /// </summary>
        public static string SETTINGS_ELEMENT_ALREADY_DEFINED {
            get {
                return ResourceManager.GetString("SETTINGS_ELEMENT_ALREADY_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings element undefined..
        /// </summary>
        public static string SETTINGS_ELEMENT_UNDEFINED {
            get {
                return ResourceManager.GetString("SETTINGS_ELEMENT_UNDEFINED", resourceCulture);
            }
        }
    }
}
