//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeraAI.API.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SQLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeraAI.API.Resources.Resources.SQLResources", typeof(SQLResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection is established with database;.
        /// </summary>
        public static string SQLSERVER_CONNECTIONS_NO_CONNECTION {
            get {
                return ResourceManager.GetString("SQLSERVER_CONNECTIONS_NO_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is being destroyed but connection is still open;.
        /// </summary>
        public static string SQLSERVER_DESTRUCTION_CONNECTION_STILL_OPEN {
            get {
                return ResourceManager.GetString("SQLSERVER_DESTRUCTION_CONNECTION_STILL_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Engine Message:.
        /// </summary>
        public static string SQLSERVER_PREFIX_INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("SQLSERVER_PREFIX_INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL unknown origin:.
        /// </summary>
        public static string SQLSERVER_PREFIX_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("SQLSERVER_PREFIX_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t no transaction to be commited;.
        /// </summary>
        public static string SQLSERVER_TRANSACTIONS_COMMIT_MISSED_TRANSACTION {
            get {
                return ResourceManager.GetString("SQLSERVER_TRANSACTIONS_COMMIT_MISSED_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have an open connection to initiate a transaction;.
        /// </summary>
        public static string SQLSERVER_TRANSACTIONS_CONNECTION_CLOSED {
            get {
                return ResourceManager.GetString("SQLSERVER_TRANSACTIONS_CONNECTION_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not work on SQLConnectionModes.auto with sql transactions;.
        /// </summary>
        public static string SQLSERVER_TRANSACTIONS_CONNECTIONMODE_INCONSISTENCY {
            get {
                return ResourceManager.GetString("SQLSERVER_TRANSACTIONS_CONNECTIONMODE_INCONSISTENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t no transaction to be rollback;.
        /// </summary>
        public static string SQLSERVER_TRANSACTIONS_ROLLBACK_MISSED_TRANSACTION {
            get {
                return ResourceManager.GetString("SQLSERVER_TRANSACTIONS_ROLLBACK_MISSED_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of transaction is mandatory;.
        /// </summary>
        public static string SQLSERVER_TRANSACTIONS_TRANSACTION_IS_MANDATORY {
            get {
                return ResourceManager.GetString("SQLSERVER_TRANSACTIONS_TRANSACTION_IS_MANDATORY", resourceCulture);
            }
        }
    }
}
